# Generated by Django 2.1.4 on 2019-06-18 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
