# Generated by Django 2.1.4 on 2019-06-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_videojuego_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
