# Generated by Django 2.1.4 on 2019-06-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_auto_20190617_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha',
        ),
    ]
