# Generated by Django 2.1.4 on 2019-06-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_remove_videojuego_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha',
            field=models.CharField(default='00/00/0000', max_length=50),
            preserve_default=False,
        ),
    ]
