"""descripcion en cuentas

Revision ID: 6c0f3a5ca80e
Revises: 74d20c936682
Create Date: 2019-08-07 02:12:08.413105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0f3a5ca80e'
down_revision = '74d20c936682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('descripcion', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'descripcion')
    # ### end Alembic commands ###
