"""flask-login

Revision ID: 74d20c936682
Revises: b3d5a09e3ebe
Create Date: 2019-08-06 19:12:28.874184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d20c936682'
down_revision = 'b3d5a09e3ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('conectado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'conectado')
    # ### end Alembic commands ###
