"""Valoracion con comentario

Revision ID: b3d5a09e3ebe
Revises: e8f7a9df70e5
Create Date: 2019-08-02 16:36:05.435670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d5a09e3ebe'
down_revision = 'e8f7a9df70e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valoracion', sa.Column('comentario', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valoracion', 'comentario')
    # ### end Alembic commands ###
