"""roles de usuario

Revision ID: d9adfb10ac75
Revises: 6c0f3a5ca80e
Create Date: 2019-08-07 12:41:33.193529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9adfb10ac75'
down_revision = '6c0f3a5ca80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('role', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'role')
    # ### end Alembic commands ###
