"""Inicio

Revision ID: dc35f06443ed
Revises: 
Create Date: 2019-07-31 14:22:41.095962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc35f06443ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plataforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha_estreno', sa.Date(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('imagen', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('imagen', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha_estreno', sa.Date(), nullable=True),
    sa.Column('imagen', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabecera', sa.String(length=100), nullable=True),
    sa.Column('tema', sa.Enum('oscuro', 'claro', name='temas'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videojuego_genero',
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('videojuego_id', 'genero_id')
    )
    op.create_table('videojuego_plataforma',
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.Column('plataforma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataforma.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('videojuego_id', 'plataforma_id')
    )
    op.create_table('videojuego_listado',
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.Column('listado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listado_id'], ['listado.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('videojuego_id', 'listado_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videojuego_listado')
    op.drop_table('videojuego_plataforma')
    op.drop_table('videojuego_genero')
    op.drop_table('listado')
    op.drop_table('videojuego')
    op.drop_table('usuario')
    op.drop_table('plataforma')
    op.drop_table('genero')
    # ### end Alembic commands ###
