"""Valoracion

Revision ID: e8f7a9df70e5
Revises: dc35f06443ed
Create Date: 2019-08-02 16:17:17.180191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f7a9df70e5'
down_revision = 'dc35f06443ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valoracion',
    sa.Column('listado_id', sa.Integer(), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listado_id'], ['listado.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('listado_id', 'videojuego_id')
    )
    op.drop_table('videojuego_listado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videojuego_listado',
    sa.Column('videojuego_id', sa.INTEGER(), nullable=False),
    sa.Column('listado_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['listado_id'], ['listado.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('videojuego_id', 'listado_id')
    )
    op.drop_table('valoracion')
    # ### end Alembic commands ###
